auto:
    create:
        topics:
            enable: true
datasource: ''
ddl-auto: update
error: ''
hibernate: ''
include-stacktrace: on_param
jpa: ''
password: root
server: ''
spring: ''
spring.kafka.producer.bootstrap-servers: 127.0.0.1:9092
spring.kafka.producer.group-id: group_id
topic:
    name:
        producer: topico.comando.teste
url: jdbc:mysql://localhost:3306/desafio?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
username: root
